#! /bin/bash

if [ "$1" == "" ] || [ "$2" == "" ]; then
	echo "Error: missing parameter(s)."
	exit -1

else

	echo "Creating site "$2" for user "$1"..."

	test -e /etc/apache2/sites-available/$2 && echo "Error: site "$2" already exits!" && exit -1

	test ! -e /home/$1 && echo "Error: can't find user directory: "$1 && exit -1

	echo "creating directory \"/home/"$1"/sites/"$2"\""
	mkdir -p /home/$1/sites/$2/

	echo "creating directory \"/home/"$1"/sites/logs/"$2"\""
	mkdir -p /home/$1/sites/logs/$2/

	echo "creating log files..."
	touch /home/$1/sites/logs/$2/error.log
	touch /home/$1/sites/logs/$2/access.log

	echo "chown..."
	chown $1 -R /home/$1/sites/$2/
	chown $1 -R /home/$1/sites/logs/$2/

	echo "Writing into /etc/apache2/sites-available/"$2
	printf "<VirtualHost *:80>\n  ServerAdmin $1@localhost\n\n  DocumentRoot /home/$1/sites/$2/\n  ServerName $2\n  ServerAlias \n  AssignUserId $1 $1\n\n  <Directory /home/$1/sites/$2>\n      Options Indexes FollowSymLinks MultiViews\n      AllowOverride All\n      Order allow,deny\n      allow from all\n  </Directory>\n\n  ErrorLog /home/$1/sites/logs/$2/error.log\n  LogLevel warn\n  CustomLog /home/$1/sites/logs/$2/access.log combined\n</VirtualHost>\n" >> /etc/apache2/sites-available/$2

	if [ -e /etc/awstats/ ]; then
		echo "setting up awstats..."
		printf "Include \"awstats.conf\"\nLogFile=\"/home/$1/sites/logs/$2/access.log\"\nSiteDomain=\"$2\"\nDirData=\"/var/lib/awstats\"\nHostAliases=\"\"\n" >> /etc/awstats/awstats.$2.conf

	fi

	echo "Run a2ensite "$2" and service apache2 reload to take effects!"

fi
